
[env]
TERM = "xterm-256color"

[window]
opacity = 0.9
blur = true

decorations = "buttonless"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#11121D"
foreground = "#A9B1D6"

[colors.normal]
black = "#32344A"
red = "#F7768E"
green = "#9ECE6A"
yellow = "#E0AF68"
blue = "#E0AF68"
magenta = "#AD8EE6"
cyan = "#449DAB"
white = "#787C99"

[colors.bright]
black = "#444B6A"
red = "#FF7A93"
green = "#B9F27C"
yellow = "#FF9E64"
blue = "#7DA6FF"
magenta = "#BB9AF7"
cyan = "#0DB9D7"
white = "#ACB0D0"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "BoldItalic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "MediumItalic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[scrolling]
history = 10000
multiplier = 3

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5

[cursor.style]
shape = "Block"
blinking = "Off"

[selection]
save_to_clipboard = false

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[general]

live_config_reload = true
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[terminal]

[terminal.shell]
program = "/usr/bin/zsh"
