#!/usr/bin/env bash
#    ____         __       ____               __     __
#   /  _/__  ___ / /____ _/ / / __ _____  ___/ /__ _/ /____ ___
#  _/ // _ \(_-</ __/ _ `/ / / / // / _ \/ _  / _ `/ __/ -_|_-<
# /___/_//_/___/\__/\_,_/_/_/  \_,_/ .__/\_,_/\_,_/\__/\__/___/
#                                 /_/
#

# Check if command exists
_checkCommandExists() {
    cmd="$1"
    if ! command -v "$cmd" >/dev/null; then
        echo 1
        return
    fi
    echo 0
    return
}

_isInstalled() {
    package="$1"
    case $install_platform in
        arch)
            check="$($aur_helper -Qs --color always "${package}" | grep "local" | grep "${package} ")"
            ;;
        fedora)
            check="$(dnf repoquery --quiet --installed ""${package}*"")"
            ;;
        *) ;;
    esac

    if [ -n "${check}" ]; then
        echo 0 #'0' means 'true' in Bash
        return #true
    fi
    echo 1 #'1' means 'false' in Bash
    return #false
}

# ------------------------------------------------------
# Confirm Start
# ------------------------------------------------------

sleep 1
clear
if command -v figlet &> /dev/null; then
    figlet -f smslant "Updates"
else
    echo "==== Updates ===="
fi
echo

primarycolor="#80032e"
onprimarycolor="#ffffff"
onsurfacecolor="#48f7fa"

if gum confirm \
    --selected.background=$primarycolor \
    --selected.foreground=$onprimarycolor \
    --prompt.foreground=$onsurfacecolor \
    "DO YOU WANT TO START THE UPDATE NOW?"; then
    echo
    echo ":: Update started..."
elif [ $? -eq 130 ]; then
    exit 130
else
    echo
    echo ":: Update canceled."
    exit
fi

# ----------------------------------------------------- 
# Install update
# ----------------------------------------------------- 

# Arch
if [[ $(_checkCommandExists "pacman") == 0 ]]; then

    if command -v yay &> /dev/null; then
        yay -Syu --noconfirm
    elif command -v paru &> /dev/null; then
        paru -Syu --noconfirm
    else
        echo ":: No AUR helper found"
    fi

# Fedora
elif [[ $(_checkCommandExists "dnf") == 0 ]]; then
    sudo dnf upgrade -y
else
    echo ":: ERROR - Platform not supported"
    echo "Press [ENTER] to close."
    read -r
fi
echo

# Flatpak
echo ":: Searching for Flatpak updates..."
flatpak update -y
echo

# Reload Waybar
pkill -RTMIN+1 waybar 2>/dev/null || true

# Finishing
echo ":: Update complete! Press [ENTER] to close."
read -r
