# -----------------------------------------------------
# Autostart
# -----------------------------------------------------

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

# exec-once = hyprpaper
exec-once = awww-daemon
exec-once = ~/.config/waybar/scripts/launch.sh
exec-once = brightnessctl set 30%

exec-once = qs -c ~/.config/quickshell

# Start Listeners
exec-once=~/.config/supersection/listeners.sh --startall

# Start Polkit
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Restore Wallpaper
exec-once = ~/.config/supersection/scripts/supersection-wallpaper-app --restore

# Autostart script
exec-once = ~/.config/supersection/scripts/supersection-autostart

# Load GTK settings
exec-once = ~/.config/hypr/scripts/gtk.sh

# Load Notification Daemon
exec-once = swaync

# Using hypridle to start hyprlock
exec-once = hypridle

# Load cliphist history
exec-once = wl-paste --watch cliphist store

# Start autostart cleanup
exec-once = ~/.config/hypr/scripts/cleanup.sh

# Load configuration from SuperSection Hyprland Settings App
exec = ~/.config/com.supersection.hyprlandsettings/hyprctl.sh
